- name: Variables
  hosts: localhost
  vars:
   COURSE: "Devops"
   TRAINER: "Siva"
   DURATION: "120 hours"
  tasks:
  - name: print override information
    vars:
     COURSE: "Terraform"
    ansible.builtin.debug:
     msg: "Hello we are learning {{COURSE}} from {{TRAINER}}, with in {{DURATION}}"
  
  - name: print information
    ansible.builtin.debug:
     msg: "Hello we are learning {{COURSE}} from {{TRAINER}}, with in {{DURATION}}"
