- name: variable preference
  hosts: localhost
  #vars:
   #WISHES: "wishes from PLAY variable"
  #vars_files:
  #- vars.yaml
  #vars_prompt:
  #- name: WISHES
   # prompt: please enter wishes
    #private: false
  tasks:
   - name: check preference
     #vars:
     # WISHES: "wishes from TASK variable"
     ansible.builtin.debug:
      msg: "Hi {{WISHES}}"

# 1.arguments
# 2.Task variable
# 3.vars from files
# 4. vars from prompt
# 5. vars from Play variables
# 6. vars from inventory
# 7. role level