- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      msg: "{{ item }}"
      state: latest
      enabled: yes
    loop: 
    - mysql
    - nginx
    - postfix