- name: install packages
  hosts: web
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      msg: "{{ item }}"
      state: install_weak_deps
    loop: 
    - mysql
    - nginx
    - postfix