- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      msg: "{{ item.name }}"
      state: "{{ item.state}}"
      enabled: yes
    loop: 
    - {name: 'mysql', state: 'latest'}
    - {name: 'nginx', state: 'absent'}
    - {name: 'postfix', state: 'absent'}